[package]
name = "supercaching-dns"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
hickory-client = "0.24.1"
hickory-resolver = "0.24.1"
hickory-server = "0.24.1"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
